### ISSUE TITLE
Take into account organization repositories

### ISSUE THREAD

**Issue by astrofrog** [vdaubry/github-awards#3]
Some users have repositories in organization accounts - it would be nice to take this into account. Maybe one could look at the fraction of commits made to a repo and share out the stars that way. So say two users contribute to a 1000 star repo equally, they would both get 500 stars. Or something like this?

**Comment by larruda** [comment]
Following his idea, I think currently the ranking should be to projects/repositories and not for people. I could potentially be contributing to thousands of repositories and have none. It looks like this situation does not count right?

**Comment by astrofrog** [comment]
@larruda - yes, that's a better way of putting it!

**Comment by vdaubry** [comment]
At the moment i only take into account repositories you own. To include repositories you contribute to it would require to evaluate your contribution (number of lines commited ?)
You can't get all stars only for updated a readme...

In any case we'll have to use [githubarchive](https://www.githubarchive.org) in order to get that kind of information.
I'm going to think about what's feasible. If you have any suggestion on how to include contributions to repo in the ranking i'm also interested.

**Comment by astrofrog** [comment]
@vdaubry - fraction of commits to a repository is probably a good place to start. Number of lines is not meaningful (because of e.g. data files, etc.). Most highly starred repositories won't accept arbitrarily large numbers of non-useful commits. I'd argue you should get a fraction of stars that reflects your contribution, so e.g. someone contributing 10% of the commits of a 1000 star repo gets 100 stars. So if you contribute one commit to a README, you probably won't get much.

**Comment by zoechi** [comment]
+1
I have all open source projects I take serious in a organization account of mine.

**Comment by JedWatson** [comment]
+1

I think it would be a shame if this sort of site disincentives project maintainers from moving their repos into orgs. I've written 99% of KeystoneJS but late last year I moved it into its own org as a recognition of the growing community and contributor base. This opened up a lot of enthusiasm around the project (it became a community identity rather than being seen as my own vanity project) and I think that is a great thing to encourage developers to do.

If I were concerned about my ranking on this site, though, I have 173 stars instead of ~5k partly because of this. And therefore if I were concerned about my ranking on this site, I would be incentivised _not_ to move the repo to an org, and create a community identity around my project.

**Comment by jdalton** [comment]
:+1:

**Comment by philipobenito** [comment]
Definitely would agree that there's a better way to rank. A lot of developers will store their open source repos in an org and only use their personal accounts for contributions and fiddling therefore the current algorithm doesn't provide the best accuracy.

Could see this being a great tool though for many reasons if the ranking accuracy is improved.

**Comment by goetas** [comment]
> You can't get all stars only for updating a readme...

If you are a contributor of a project most probably you changed something more than a readme file

So, why do not assign all the stars from org repos to each member? (Looking at the commit history will be very painful)

**Comment by eveliotc** [comment]
+1 I usually put the high profile stuff under my org e.g https://github.com/telly/MrVector

**Comment by lenville** [comment]
+1 Stars from a forked repo are counted independent of the source repo, such as [ [source](https://github.com/lukehoban/es6features) | [fork](https://github.com/lenville/es6features) ].

And even forks have their own fork => [check `$('.current-repository')`](https://github.com/lenville/es6features/network/members)

I am a novice at github and I think counting these in may encourage me a lot for making greater contributions.

**Comment by vdaubry** [comment]
@goetas : Just to be sure we're talking about the same thing i'll take an example :

I see your are listed as contributor of the [html5-php](https://github.com/Masterminds/html5-php/graphs/contributors) repo.
The stats indicate that your are a major contributor (almost 50 commits with 12k+ LOC)

But on the same contributor list your have [cognifloyd](https://github.com/cognifloyd) whith only 1 commit with a total of 6 LOC contributed to the repo.
And this commit is actually an update to the project documentation ;)

The only way to give stars to project contributors is looking at the commit history, which is quite complex as you said.
I'm looking for help to build this and opened a discussion on #30

**Comment by goetas** [comment]
@vdaubry Now i see, you are right.

The solution proposed by you on #30 looks better (`https://developer.github.com/v3/repos/#list-contributors`), but instead of calling the API  on each repo, why do not call this only if the user request a refresh?
Doing this you can skip a lot of low-ranked users... I think that more than 60% of github users have a very low public activity, and if they are not interested in github awards, there is no need to waste bandwidth and CPU.

**Comment by natebrunette** [comment]
+1

I also publish everything serious to an organization.

**Comment by vdaubry** [comment]
I added the organizations into the ranking.

@natebrunette , here is the page for the 'tebru' org : http://github-awards.com/users/search?login=tebru

I'm colsing this issue, feel free to re-open it if something is wrong.

**Comment by natebrunette** [comment]
Sweet!  Thanks for doing that.

Will it refresh automatically?  I don't get the button because you can't login as organizations, I'm guessing.

**Comment by goetas** [comment]
You added organizations, members of an organization will not benefit for their commits. Is it true?

**Comment by vdaubry** [comment]
> You added organizations, members of an organization will not benefit for their commits. Is it true?

That's right. See the previous comment about that subject : https://github.com/vdaubry/github-awards/issues/3#issuecomment-90499247

**Comment by vdaubry** [comment]
@natebrunette : yes organizations will refresh everytime they appear in the Github Archive (based on events such as commits, PR, etc)

**Comment by schmunk42** [comment]
It does not find City nor Country, i.e

- http://github-awards.com/users/search?login=dmstr
- http://github-awards.com/users/search?login=tebru

In my case `dmstr` has the same location as my [personal account](https://github.com/schmunk42).
