### ISSUE TITLE
Is it possible to specify the primary language of a project?

### ISSUE THREAD

**Issue by lhorie** [vdaubry/github-awards#54]
I'm getting a lot of stars for HTML, presumably because of the large amount of HTML documentation files in my most active repo, even though it's a javascript project. ([link](https://github.com/lhorie/mithril.js))

**Comment by vdaubry** [comment]
Unfortunately no, this is discussed in the Github FAQ : https://help.github.com/articles/my-repository-is-marked-as-the-wrong-language/

Have a look at this issue for more details : https://github.com/vdaubry/github-awards/issues/6

Hope that helps, I'm closing this issue since it's a Github related problem.
