### ISSUE TITLE
XSS Vulnerability

### ISSUE THREAD

**Issue by mikicaivosevic** [vdaubry/github-awards#79]
[github-awards](http://github-awards.com) is vulnerable on XSS. 

PoC: http://github-awards.com/users?utf8=✓&type=country&language=JavaScript&country=[vuln]

GET param "country" is vulnerable on XSS. I have fixed that before few months, but you need to do pull on your server.

**Comment by vdaubry** [comment]
First of all, thanks a lot for raising this issue !
It's fixed by #80

A few interesting notes :

* Your pull request #56 was merged, the problem was that since the user input for country is interpolated in a string we had to espace it inside the string :

https://github.com/vdaubry/github-awards/pull/80/files#diff-e065be9112de8c01377ece2d65c3cb71L24

* On Chrome and Safari if you actually try to display some javascript it will display a blank page.
But on Firefox the JS is executed.
The problem is fixed on github-awards.com, but you can reproduce this behavior locally.
This URL displays a hello alert box on Firefox but displays a blank page on Chrome and Safari :

[http://localhost:3000/users?utf8=%E2%9C%93&type=country&language=JavaScript&country=%3Cscript%3Ealert%28%27hello%27%29%3B%3C%2Fscript%3E](http://localhost:3000/users?utf8=%E2%9C%93&type=country&language=JavaScript&country=%3Cscript%3Ealert%28%27hello%27%29%3B%3C%2Fscript%3E)
