### ISSUE TITLE
Category duplication

### ISSUE THREAD

**Issue by LukyVj** [vdaubry/github-awards#98]
As you can see in this screenshot, the CSS ranking section is duplicated, and it says I have 1 Repo, but I have like 80 repos.

![](http://puu.sh/maon7/d3c6228fa3.png)

**Comment by vdaubry** [comment]
Thanks for reporting this issue, i'm looking into this.

**Comment by vdaubry** [comment]
@LukyVj : There was a bug in the job that pulls data from Github Archive (languages were case-sensitive)
The bug is fixed and i'm running a script to update remaining data in database.

Everything is back to normal for the top 20 languages and should be good by tomorrow for all languages.

I'm closing this issue: i'll re-open it if this problem happens again.

**Comment by LukyVj** [comment]
Thanks ! You rock <3
